data-loader:
  running: true
  threads: 5
  sqs: data-loader-default-queue
  s3: data-loader-default-s3
  efs: /data/loader/default
  es: localhost
  esSniff: false
  loadRandom: false
  enableLogging: true


---
spring:
  profiles: dev

data-loader:
  running: false
  threads: 50
  sqs: data-loader-dev-quque
  s3: data-loader-dev-s3
  efs: /data/loader/dev/
  es: 10.1.9.15,10.1.9.21
  esSniff: false
  loadRandom: false
  enableLogging: true
