rene-drf:
  running: true
  threads: 5
  sqs: drf-default-queue
  s3: drf-default-s3
  efs: /media/drf/
  es: localhost
  esSniff: false
  loadRandom: false
  enableLogging: true


---
spring:
  profiles: dev

rene-drf:
  running: false
  threads: 50
  sqs: drf-dev-queue
  s3: drf-dev-s3
  efs: /media/efs/
  es: 10.1.9.15,10.1.9.21
  esSniff: false
  loadRandom: false
  enableLogging: true
